server {
    listen 80;

    location ^~ /Identity/ {
        proxy_pass http://authservice:8080;

        #proxy_set_header Host $http_host; # I wonder why it works here without Host header?

        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;
        #proxy_set_header X-Real-IP $remote_addr;
    }

    # These endpoints are for Identity custom Admin dashboard
    location = /Admin {
        return 302 $scheme://$http_host/Admin/Dashboard;
    }
    location = /Admin/ {
        return 302 $scheme://$http_host/Admin/Dashboard;
    }

    # Rewrite rules for /Admin/* endpoints for Identity pages
    location ^~ /Admin/ {
        proxy_pass http://authservice:8080;

        proxy_set_header Host $http_host; # Without this it breaks

        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-Proto $scheme;

        #proxy_redirect off;
    }

    location /api/auth/ {
        rewrite ^/api/auth/(.*)$ /auth/$1 break;
        proxy_pass http://authservice:8080;
    }

    location /api/power {
        rewrite ^/api/power/(.*)$ /$1 break;
        proxy_pass http://powerservice:8080;
    }

    location /api/inference {
        rewrite ^/api/inference/(.*)$ /$1 break;
        proxy_pass http://inferenceservice:8080;
    }

    # For any other /api/ routes (useful when there are no service containers inside network)
    # GET requests to /api/ get redirected to static HTML
    location ^~ /api/ {
        return 404;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}