// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerService.Data;

#nullable disable

namespace powerservice.Migrations
{
    [DbContext(typeof(PowerDataContext))]
    partial class PowerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerService.Models.PowerDataHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ATLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("at_load_value");

                    b.Property<double?>("BELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("be_load_value");

                    b.Property<double?>("BGLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("bg_load_value");

                    b.Property<double?>("CHLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ch_load_value");

                    b.Property<double?>("CYLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("cy_load_value");

                    b.Property<double?>("CZLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("cz_load_value");

                    b.Property<double?>("DELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("de_load_value");

                    b.Property<double?>("DKLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("dk_load_value");

                    b.Property<double?>("EELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ee_load_value");

                    b.Property<double?>("ESLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("es_load_value");

                    b.Property<double?>("FILoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("fi_load_value");

                    b.Property<double?>("FRLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("fr_load_value");

                    b.Property<double?>("GBLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("gb_load_value");

                    b.Property<double?>("GRLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("gr_load_value");

                    b.Property<double?>("HRLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("hr_load_value");

                    b.Property<double?>("HULoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("hu_load_value");

                    b.Property<double?>("IELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ie_load_value");

                    b.Property<double?>("ITLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("it_load_value");

                    b.Property<double?>("LTLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lt_load_value");

                    b.Property<double?>("LULoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lu_load_value");

                    b.Property<double?>("LVLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lv_load_value");

                    b.Property<double?>("MELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("me_load_value");

                    b.Property<double?>("NLLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("nl_load_value");

                    b.Property<double?>("NOLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("no_load_value");

                    b.Property<double?>("PLLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("pl_load_value");

                    b.Property<double?>("PTLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("pt_load_value");

                    b.Property<double?>("ROLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ro_load_value");

                    b.Property<double?>("RSLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("rs_load_value");

                    b.Property<double?>("SELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("se_load_value");

                    b.Property<double?>("SILoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("si_load_value");

                    b.Property<double?>("SKLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("sk_load_value");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double?>("UALoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ua_load_value");

                    b.HasKey("Id");

                    b.ToTable("PowerDataHour", (string)null);
                });

            modelBuilder.Entity("PowerService.Models.PowerDataQuarter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ATLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("at_load_value");

                    b.Property<double?>("BELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("be_load_value");

                    b.Property<double?>("DELoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("de_load_value");

                    b.Property<double?>("HULoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("hu_load_value");

                    b.Property<double?>("LULoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lu_load_value");

                    b.Property<double?>("NLLoadValue")
                        .HasColumnType("double precision")
                        .HasColumnName("nl_load_value");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("PowerDataQuarter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
